spring:
  application:
    name: gateway-demo
  profiles:
    active: pro

youngsun:
  mqtt:
    username: server
    password: Ale123456
    url: tcp://youngsunnb.com:1883
    client.id: demo
    completionTimeout: 3000
    default:
      receiveTopic: a/b/c/d/#,demo/+/+/+
  elasticsearch:
    host: 127.0.0.1
    port: 9200
    scheme: http
    username: ''
    password: ''
#  elasticsearch:
#    host: qingcloud.*********
#    port: 9200
#    scheme: http
#    username: 'elastic'
#    password: '+fyIfF0AqFb7A=klPIJO'

logging:
  level:
    tracer: TRACE
